"""Criacao da tabela Experimentos

Revision ID: 057e4148f117
Revises: d9ad6f61f540
Create Date: 2019-07-22 21:21:40.496564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057e4148f117'
down_revision = 'd9ad6f61f540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodoInicio', sa.DateTime(), nullable=False),
    sa.Column('periodoFim', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experimentos')
    # ### end Alembic commands ###
