"""Adição da classe status

Revision ID: 2996b6958087
Revises: 2c678d7078cc
Create Date: 2019-07-14 16:18:20.868434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2996b6958087'
down_revision = '2c678d7078cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('laboratorios', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'laboratorios', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'laboratorios', type_='foreignkey')
    op.drop_column('laboratorios', 'status_id')
    op.drop_table('status')
    # ### end Alembic commands ###
