"""Criacao da Model Instituicao

Revision ID: 3fbbff1e59af
Revises: 53ae2cb2a02c
Create Date: 2019-08-14 21:56:21.875870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbbff1e59af'
down_revision = '53ae2cb2a02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instituicoes')
    # ### end Alembic commands ###
