"""Alteracao do campo dia Detalhamentos

Revision ID: 40457bd6281b
Revises: 790325bac30e
Create Date: 2019-08-15 23:26:54.073838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40457bd6281b'
down_revision = '790325bac30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalhamentos', 'hora_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('detalhamentos', 'hora_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalhamentos', 'hora_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('detalhamentos', 'hora_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
