"""Removendo a restrição dos campos Detalhamentos

Revision ID: 790325bac30e
Revises: 7eceb5a4b91e
Create Date: 2019-08-15 22:56:58.956809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '790325bac30e'
down_revision = '7eceb5a4b91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.alter_column('detalhamentos', 'hora_fim',
#               existing_type=postgresql.TIMESTAMP(),
#               nullable=True)
#    op.alter_column('detalhamentos', 'hora_inicio',
#               existing_type=postgresql.TIMESTAMP(),
#               nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.alter_column('detalhamentos', 'hora_inicio',
#               existing_type=postgresql.TIMESTAMP(),
#               nullable=False)
#    op.alter_column('detalhamentos', 'hora_fim',
#               existing_type=postgresql.TIMESTAMP(),
#               nullable=False)
    pass
    # ### end Alembic commands ###
