"""Criacao Model Convênios

Revision ID: 7b7c737cde8a
Revises: 3fbbff1e59af
Create Date: 2019-08-14 23:01:14.167818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7c737cde8a'
down_revision = '3fbbff1e59af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
