"""Criacao Model Convênios

Revision ID: 7b7c737cde8a
Revises: 3fbbff1e59af
Create Date: 2019-08-14 23:01:14.167818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7c737cde8a'
down_revision = '3fbbff1e59af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instituicoes', sa.Column('complemento', sa.String(length=100), nullable=True))
    op.add_column('instituicoes', sa.Column('numero', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instituicoes', 'numero')
    op.drop_column('instituicoes', 'complemento')
    # ### end Alembic commands ###
