"""Inserção da model de Detalhamentos

Revision ID: 7eceb5a4b91e
Revises: e5027846c107
Create Date: 2019-08-15 00:53:03.867491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eceb5a4b91e'
down_revision = 'e5027846c107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalhamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('hora_fim', sa.DateTime(), nullable=False),
    sa.Column('convenio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalhamentos')
    # ### end Alembic commands ###
