"""empty message

Revision ID: 8e11dce43500
Revises: 7b7c737cde8a
Create Date: 2019-08-15 00:35:58.374392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e11dce43500'
down_revision = '7b7c737cde8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instituicoes', sa.Column('complemento', sa.String(length=100), nullable=True))
    op.add_column('instituicoes', sa.Column('numero', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instituicoes', 'numero')
    op.drop_column('instituicoes', 'complemento')
    # ### end Alembic commands ###
