"""Correção da relação usuario-papel

Revision ID: bc86fbb3c312
Revises: 41b3c2776680
Create Date: 2019-07-24 19:09:57.190676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc86fbb3c312'
down_revision = '41b3c2776680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 #   op.drop_table('usuarios_papeis')
    #op.add_column('usuarios', sa.Column('papel_id', sa.Integer(), nullable=False))
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    #op.create_foreign_key('usuarios_papeis_fk', 'usuarios', 'papeis', ['papel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('usuarios', 'papel_id')
    op.create_table('usuarios_papeis',
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('papel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], name='usuarios_papeis_papel_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='usuarios_papeis_usuario_id_fkey')
    )
    # ### end Alembic commands ###
