"""empty message

Revision ID: e5027846c107
Revises: 8e11dce43500
Create Date: 2019-08-15 00:40:55.114621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5027846c107'
down_revision = '8e11dce43500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=False),
    sa.Column('validade', sa.DateTime(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convenios')
    # ### end Alembic commands ###
