"""Modificação dos nomes dos campos da tabela agendamentos

Revision ID: f6824efd71aa
Revises: 56110e89b224
Create Date: 2019-08-03 17:07:25.445771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6824efd71aa'
down_revision = '56110e89b224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('periodo_fim', sa.DateTime(), nullable=False))
    op.add_column('agendamentos', sa.Column('periodo_inicio', sa.DateTime(), nullable=False))
    op.drop_column('agendamentos', 'periodoInicio')
    op.drop_column('agendamentos', 'periodoFim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('periodoFim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('agendamentos', sa.Column('periodoInicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('agendamentos', 'periodo_inicio')
    op.drop_column('agendamentos', 'periodo_fim')
    # ### end Alembic commands ###
