"""Criação da tabela Equipamentos

Revision ID: 62c6ce8d29ae
Revises: 2996b6958087
Create Date: 2019-07-14 18:05:41.226033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c6ce8d29ae'
down_revision = '2996b6958087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratorios', sa.Column('descricao', sa.String(length=250), nullable=True))
    op.add_column('laboratorios', sa.Column('laboratorio_id', sa.Integer(), nullable=False))
    op.add_column('laboratorios', sa.Column('nome', sa.String(), nullable=False))
    op.add_column('laboratorios', sa.Column('uri', sa.String(), nullable=False))
    op.create_foreign_key(None, 'laboratorios', 'laboratorios', ['laboratorio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'laboratorios', type_='foreignkey')
    op.drop_column('laboratorios', 'uri')
    op.drop_column('laboratorios', 'nome')
    op.drop_column('laboratorios', 'laboratorio_id')
    op.drop_column('laboratorios', 'descricao')
    # ### end Alembic commands ###
