"""Configuração do Flask Security

Revision ID: cd04ef510823
Revises: 26c5baf21c52
Create Date: 2019-07-23 21:07:59.787765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd04ef510823'
down_revision = '26c5baf21c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.add_column('papeis', sa.Column('descricao', sa.String(length=255), nullable=True))
    op.add_column('papeis', sa.Column('nome', sa.String(length=80), nullable=True))
    op.drop_constraint('papeis_name_key', 'papeis', type_='unique')
    op.create_unique_constraint(None, 'papeis', ['nome'])
    op.drop_column('papeis', 'description')
    op.drop_column('papeis', 'name')
    op.add_column('usuarios', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('nome', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'usuarios', ['email'])
    op.drop_column('usuarios', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'nome')
    op.drop_column('usuarios', 'confirmed_at')
    op.drop_column('usuarios', 'active')
    op.add_column('papeis', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('papeis', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'papeis', type_='unique')
    op.create_unique_constraint('papeis_name_key', 'papeis', ['name'])
    op.drop_column('papeis', 'nome')
    op.drop_column('papeis', 'descricao')
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['papeis.id'], name='roles_users_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name='roles_users_user_id_fkey')
    )
    # ### end Alembic commands ###
