"""Criação da tabela Equipamentos

Revision ID: d9ad6f61f540
Revises: 3f21e107bd02
Create Date: 2019-07-14 18:21:02.768027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ad6f61f540'
down_revision = '3f21e107bd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipamentos')
    # ### end Alembic commands ###
